name: function_filter
description: A Dart library for function filtering utilities, providing tools for debouncing and throttling function executions based on time intervals.
version: 2.4.1
homepage: https://github.com/Mopriestt/function_filter

environment:
  sdk: '>=2.12.0 <4.0.0'

dev_dependencies:
  test: ^1.29.0
